- name: Importar archivo configuración
  template:
          src: files/mongod.conf
          dest: /etc/mongod.conf
          owner: root
          group: root
          mode: '0644'
  # Usamos register y when para reemplazar a los handlers, ya que estos se ejecutan al final de todas las tareas
  #     y pueden dar problemas por este motivo.
  register: restart

- name: Reiniciar MongoDB
  service:
          name: mongod
          state: restarted
  when: restart.changed

- name: Abrir puerto de MongoDB
  firewalld:
          port: 27017/tcp
          permanent: true
          state: enabled
  register: firewall

- name: Reiniciar firewall
  systemd:
          name: firewalld
          state: restarted
  when: firewall.changed

- name: Crear base de datos
  community.mongodb.mongodb_shell:
          login_user: "{{ admin_user }}"
          login_password: "{{ admin_password }}"
          login_port: 27017
          db: "{{ db_name }}"
          eval: "db.createCollection('{{ collection_name }}')"

- name: Crear usuario para conexión remota
  community.mongodb.mongodb_user:
          login_user: "{{ admin_user }}"
          login_password: "{{ admin_password }}"
          db: "{{ db_name }}"
          name: "{{ remote_user }}"
          password: "{{ remote_password }}"
          state: present
          roles:
                  - readWrite
