---

###### ACTUALMENTE NO LOS USO #####
- name: Iniciar servicio httpd
  service:
          name: httpd
          state: started
          enabled: yes
  listen: "restart http"

- name: Reiniciar firewall
  service:
          name: firewalld
          state: reloaded
  listen: "restart firewalld"

- name: Reiniciar servidor
  reboot:
          reboot_timeout: 30
          post_reboot_delay: 30
  listen: "restart server"
