---
- name: Verify reverse proxy and Wordpress
  hosts: RedHat-ubi8, Debian11, Wordpress-ubi8, Wordpress-debian11
  gather_facts: true
  tasks:
          - name: Check if httpd is up and running
            uri:
                    url: http://localhost/wordpress/
                    method: POST
                    return_content: yes
                    validate_certs: no
                    status_code:
                            - 302
            register: uri_output
            failed_when: uri_output.status != 302

          - name: Success message
            debug:
                    msg: "Proxy redirects correctly"
            when: uri_output is success

- name: Verify MariaDB
  hosts: Mariadb-ubi8, Mariadb-debian11
  gather_facts: true
  tasks:
          - name: Comprobar si MariaDB está ejecutándose -- UBI
            service:
                    name: mysql
                    state: started
            register: mariadb_status_ubi
            when: ansible_distribution == "RedHat"

          - name: Comprobar si MariaDB está ejecutándose -- DEBIAN
            service:
                    name: mariadb
                    state: started
            register: mariadb_status_debian
            when: ansible_distribution == "Debian"

          - name: Print status -- UBI
            debug:
                    msg: "El servicio de MariaDB en UBI está {{ 'enabled. Starting...' if mariadb_status_ubi.changed else 'started.' }}"
            when: ansible_distribution == "RedHat"

          - name: Print status -- DEBIAN
            debug:
                    msg: "El servicio de MariaDB en DEBIAN está {{ 'enabled. Starting...' if mariadb_status_debian.changed else 'started.' }}"
            when: ansible_distribution == "Debian"

          - name: Check connection
            mysql_db:
                    login_user: wordpress-user
                    login_password: 1234
                    login_host: localhost
                    db: bdwordpress
                    state: present
            register: mariadb_connectivity

          - name: Print result
            debug:
                    msg: "La conexión a mariadb con el usuario wordpress-user fue {{ 'fallida' if mariadb_connectivity.changed else 'exitosa' }}"
