---
driver:
  name: docker

verifier:
  name: ansible

platforms:
  - name: RedHat-ubi8
    image: ubi8/python:latest
    published_ports:
            - 8080:80
    privileged: true
    pre_build_image: true
    ansible_python_interpreter: /usr/bin/python3
    # Para que systemd inicie
    command: /usr/sbin/init
    registry: false
    # Crear red
    docker_networks:
            - name: "wordpress-mariadbexterno"
              ipam_config:
                      - subnet: '10.30.50.0/24'
    networks:
            - name: "wordpress-mariadbexterno"
              ipv4_address: '10.30.50.10'

  - name: Debian11
    image: debian/python:11.9
    published_ports:
            - 9090:80
    privileged: true
    pre_build_image: true
    ansible_python_interpreter: /usr/bin/python3
    networks:
            - name: "wordpress-mariadbexterno"
              ipv4_address: '10.30.50.20'

  - name: Debian11-MariaDB
    image: debian/python:11.9
    published_ports:
            - 3306:3306
    privileged: true
    pre_build_image: true
    ansible_python_interpreter: /usr/bin/python3
    networks:
            - name: "wordpress-mariadbexterno"
              ipv4_address: '10.30.50.30'
