---

- name: Pretasks for Client2 (Apache + Wordpress)
  hosts: RedHat-ubi8, Debian11
  gather_facts: true
  tasks:
          - name: Instalar sudo - UBI
            when: ansible_distribution == "RedHat"
            yum:
                    name: sudo
                    state: present

          - name: Instalar sudo - DEBIAN
            when: ansible_distribution == "Debian"
            apt:
                    name: sudo
                    state: present
