---

- name: Pretasks for Apache installation
  hosts: all
  gather_facts: yes
  tasks:
#          - name: Actualizar paquetes - UBI
#            when: ansible_distribution == "RedHat"
#            yum:
#                    name: "*"
#                    state: latest
#            retries: 3
#            delay: 10

#          - name: Actualizar paquetes - DEBIAN
#            when: ansible_distribution == "Debian"
#            apt:
#                    name: "*"
#                    state: latest
#            retries: 3
#            delay: 10

          - name: Instalar sudo - UBI
            when: ansible_distribution == "RedHat"
            yum:
                    name: sudo
                    state: present

          - name: Instalar sudo - DEBIAN
            when: ansible_distribution == "Debian"
            apt:
                    name: sudo
                    state: present
