---
- name: Instalación de los paquetes requeridos
  apt:
          name:
                  - gnupg
                  - curl
                  - pip
                  - ufw
          state: present
  retries: 3
  delay: 10

- name: Importación de la key del repositorio
  apt_key:
          url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
          state: present
  retries: 3
  delay: 10

- name: Añadir repositorio
  become: yes
  lineinfile:
          path: "/etc/apt/sources.list.d/mongodb-org-{{ mongodb_version }}.list"
          line: "deb http://repo.mongodb.org/apt/{{ debian_version }}/mongodb-org/{{ mongodb_version }} main"
          create: yes

- name: Actualizar repositorios
  become: yes
  apt:
          update_cache: yes
  retries: 3
  delay: 10

- name: Instalar MongoDB
  apt:
          name:
                  - mongodb-org
                  - mongosh
          state: latest
  register: mongodb_install

- name: Instalar PyMongo
  pip:
          name: pymongo
          state: present
  retries: 3
  delay: 10

- name: Iniciar MongoDB
  service:
          name: mongod
          state: started
          enabled: yes

- name: Crear usuario administrador
  community.mongodb.mongodb_user:
          database: admin
          name: "{{ admin_user }}"
          password: "{{ admin_password }}"
          state: present
          roles: ["root"]
  when: mongodb_install is changed
