---

- name: Crear directorio de copias de seguridad
  file:
          path: /backup
          state: directory
          mode: '0755'

- name: Obeneter fecha y hora actual
  set_fact:
          timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"

- name: Realizar backup de la base de datos
  mysql_db:
          state: dump
          name: "{{ debian_bd_name }}"
          target: "/backup/{{ debian_bd_name }}-Debian_backup_{{ timestamp }}.sql"

- name: Comprobar si se ha realizado correctamente el backup
  stat:
          path: "/backup/{{ debian_bd_name }}-Debian_backup_{{ timestamp }}.sql"
  register: result

- name: Importar backup al control node
  fetch:
        src: "/backup/{{ debian_bd_name }}-Debian_backup_{{ timestamp }}.sql"
        dest: "/home/vagrant{{ backups_dir }}/Debian-server/"
        flat: yes
        when: result is success
