---
driver:
  name: docker
platforms:
########### CLIENTE 1 UBI8 #####################

  - name: RedHat-ubi8
    image: ubi8/python:latest
    published_ports:
            - 8080:80
    privileged: true
    pre_build_image: true
    ansible_python_interpreter: /usr/bin/python3
    # Para que systemd inicie
    command: /usr/sbin/init
    registry: false
    # Crear red
    docker_networks:
            - name: "apachewordpress"
              ipam_config:
                      - subnet: '10.30.50.0/24'
    networks:
            - name: "apachewordpress"
              ipv4_address: '10.30.50.10'

############ CLIENTE 1 DEBIAN ##################

  - name: Debian11
    image: debian/python:11.9
    published_ports:
            - 9090:80
    privileged: true
    pre_build_image: true
    ansible_python_interpreter: /usr/bin/python3
    # Crear red
    networks:
            - name: "apachewordpress"
              ipv4_address: '10.30.50.20'

############ WORDPRESS PRUEBA ##################

  - name: Wordpress
    image: wordpress/python:latest
    published_ports:
            - 7070:80
    privileged: true
    pre_build_image: true
    # Crear red
    networks:
            - name: "apachewordpress"
              ipv4_address: '10.30.50.30'
    environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: prueba
            WORDPRESS_DB_PASSWORD: 1234
            WORDPRESS_DB_NAME: bdwordpress
    volumes:
            - "wordpress:/var/www/html"

############ MYSQL PRUEBA ######################

  - name: mysql
    image: mysql:8.0
    published_ports:
            - 3306:3306
    privileged: true
    pre_build_image: true
    # Crear red
    networks:
            - name: "apachewordpress"
              ipv4_address: '10.30.50.40'
    environment:
            MYSQL_DATABASE: bdwordpress
            MYSQL_USER: prueba
            MYSQL_PASSWORD: 1234
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
            - "db:/var/lib/mysql"

