---

- name: Pretask for Client1 (Apache as Reverse Proxy)
  hosts: RedHat-ubi8, Debian11, Wordpress
  gather_facts: yes
  tasks:
          - name: Instalar sudo - UBI
            when: ansible_distribution == "RedHat"
            yum:
                    name: sudo
                    state: present

          - name: Instalar sudo - DEBIAN
            when: ansible_distribution == "Debian"
            apt:
                    name: sudo
                    state: present

          - name: Reiniciar Apache - WORDPRESS
            when: ansible_hostname == "Wordpress"
            service:
                    name: apache2
                    state: restarted
