---

- name: Pretask for Client1 (Apache as Reverse Proxy
  hosts: all
  gather_facts: yes
  tasks:
          - name: Instalar sudo - UBI
            when: ansible_distribution == "RedHat"
            yum:
                    name: sudo
                    state: present

          - name: Instalar sudo - DEBIAN
            when: ansible_distribution == "Debian"
            apt:
                    name: sudo
                    state: present
