---

- name: Crear directorio backup
  become: true
  file:
          path: /backup
          state: directory

- name: Buscar archivos en el directorio
  find:
    paths: "{{ backup_dir_redhat }}"
    patterns: "*.sql"
    file_type: file
  register: found_files
  delegate_to: "{{ backup_server }}"

- name: Comprobar content found_files
  debug:
    var: found_files

- name: Seleccionar el último archivo
  set_fact:
    last_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"
  delegate_to: "{{ backup_server }}"
  
- name: Copiar el archivo de backup al servidor de base de datos
  copy:
    src: "{{ last_file.path }}"
    dest: "/backup/restore.sql"
  register: backup_copied

- name: Restaurar base de datos
  mysql_db:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      name: "{{ db_name }}"
      state: import
      target: /backup/restore.sql
  when: backup_copied is changed
